### ISSUE TITLE
"countof" compiler issue with 2.4.0

### ISSUE THREAD

**Issue by cyberman54** [Makuna/Rtc#179]
Since upgrade vom 2.3.7 to 2.4.0 i'm facing a compiler issue:

`.pio/libdeps/usb/RTC/src/RtcDateTime.h:513:20: error: 'countof' was not declared in this scope`

Looks like something goes wrong with the #define countof

**Comment by cyberman54** [comment]
This was a false positive due to inappropriate includes in the calling program.
